### ISSUE TITLE
Create CRUDS for all tables so that users have full interactivity with database

### ISSUE THREAD

**Issue by OhlhJames** [OhlhJames/Project2-Group6#38]
Create CRUDS for all Tables:

Produce: ->
Get Route: Allows users to generate pages of produce
Post Route: Allows farmers to post produce
Update Route: Allows farmers to update prices and availability of produce as time passes 
Delete: Allows farmers to delete produce they no longer produce

Farmer: ->
Get Route: Allows users to generate pages of farmers
Post Route: Allows users to become farmers
Update Route: Allows users to update descriptions, locations, etc. on their farms
Delete Route: Allows users to delete their farm if they no longer produce any produce

Review: ->
Get Route: Allows Users to see reviews by product or just all reviews
Post Route: Allows users to make reviews for products they have used
Delete Route: Allows users to delete reviews

**Comment by OhlhJames** [comment]
Post: Produce
Post: Review 
Post: Farmer

**Comment by Benbrechter** [comment]
What Http routes we have completed 
post'/produce'
post'/farmer'
post'/reviews'

get'/reviews/:produceId'
get'/Produce'

**Comment by Benbrechter** [comment]
all of the crud reviews routes are done
